// Code generated by "stringer -type tokenType"; DO NOT EDIT.

package asm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[eof-0]
	_ = x[lineStart-1]
	_ = x[lineEnd-2]
	_ = x[invalidToken-3]
	_ = x[identifier-4]
	_ = x[dottedIdentifier-5]
	_ = x[variableIdentifier-6]
	_ = x[labelRef-7]
	_ = x[dottedLabelRef-8]
	_ = x[label-9]
	_ = x[dottedLabel-10]
	_ = x[numberLiteral-11]
	_ = x[stringLiteral-12]
	_ = x[openParen-13]
	_ = x[closeParen-14]
	_ = x[comma-15]
	_ = x[arithPlus-16]
	_ = x[arithMinus-17]
	_ = x[arithMul-18]
	_ = x[arithDiv-19]
	_ = x[arithMod-20]
	_ = x[arithLshift-21]
	_ = x[arithRshift-22]
	_ = x[arithAnd-23]
	_ = x[arithOr-24]
	_ = x[arithHat-25]
	_ = x[directive-26]
	_ = x[instMacroIdent-27]
	_ = x[openBrace-28]
	_ = x[closeBrace-29]
}

const _tokenType_name = "eoflineStartlineEndinvalidTokenidentifierdottedIdentifiervariableIdentifierlabelRefdottedLabelReflabeldottedLabelnumberLiteralstringLiteralopenParencloseParencommaarithPlusarithMinusarithMularithDivarithModarithLshiftarithRshiftarithAndarithOrarithHatdirectiveinstMacroIdentopenBracecloseBrace"

var _tokenType_index = [...]uint16{0, 3, 12, 19, 31, 41, 57, 75, 83, 97, 102, 113, 126, 139, 148, 158, 163, 172, 182, 190, 198, 206, 217, 228, 236, 243, 251, 260, 274, 283, 293}

func (i tokenType) String() string {
	if i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
