// Code generated by "stringer -type ArithOp"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArithPlus-1]
	_ = x[ArithMinus-2]
	_ = x[ArithMul-3]
	_ = x[ArithDiv-4]
	_ = x[ArithMod-5]
	_ = x[ArithLshift-6]
	_ = x[ArithRshift-7]
	_ = x[ArithAnd-8]
	_ = x[ArithOr-9]
	_ = x[ArithXor-10]
}

const _ArithOp_name = "ArithPlusArithMinusArithMulArithDivArithModArithLshiftArithRshiftArithAndArithOrArithNot"

var _ArithOp_index = [...]uint8{0, 9, 19, 27, 35, 43, 54, 65, 73, 80, 88}

func (i ArithOp) String() string {
	i -= 1
	if i >= ArithOp(len(_ArithOp_index)-1) {
		return "ArithOp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ArithOp_name[_ArithOp_index[i]:_ArithOp_index[i+1]]
}
